### ISSUE TITLE
Add code of conduct to /Hackathons/*

### ISSUE THREAD

**Issue by frankcash** [HackerCollective/resources#16]
It'd be really cool if we could keep a copy of the code of conduct in here :^).

Anyone who want's to do this go ahead.

**Comment by mrcoven94** [comment]
I can merge that ! I pull it over.

**Comment by frankcash** [comment]
:+1:

**Comment by mahirk** [comment]
Which one?

The hackercodeofconduct.org or the one posted on HH yesterday?

**Comment by mrcoven94** [comment]
This one , https://github.com/dragonai/hackathon-code-of-conduct

**Comment by kritinvij** [comment]
this is awesome

**Comment by frankcash** [comment]
This issue is closed as of a19e812c30567711461cd8b89371ec0588808281

**Comment by mahirk** [comment]
@frankcash what happened to the README file?

**Comment by frankcash** [comment]
I put everything in code tags, if others do not think that it looks good, please add suggestions.  The list style we had before was not too appealing (in my opinion).

**Comment by mrcoven94** [comment]
lets try it in a table?
Hackathons | Scholarships | Frontend | Backend | Mobile | General Programming ?
Thoughts? Tables are pretty lol. 
@frankcash @mahirk
