### ISSUE TITLE
Readme Discussion

### ISSUE THREAD

**Issue by mahirk** [HackerCollective/resources#18]
1. @mrcoven94 @frankcash Github doesn't have UMLs in their MD right? That may look good, I feel as if links may be necessary, just so its easier for people to find (when there are many more files)
2. Where should we host a site if we plan on hosting one?

**Comment by frankcash** [comment]
I'm pretty sure they don't.

**Comment by mrcoven94** [comment]
I don' t think they have em either...  hmm. Links are going to necessary, I agree (y)

**Comment by frankcash** [comment]
This issue will now cover the hosting discussion too.

**Comment by mrcoven94** [comment]
So, if its static, GH hosting, not static, heroku, docker? Love hackerque.io

**Comment by frankcash** [comment]
@mrcoven94 I think if it's static GH hosting would be fine, I have a node.js data aggregation site currently running on `hackerqueue.io.` The site is hosted on DigitalOcean with an Ubuntu 14.04 machine, so you would just need to SSH to it or I could set up a daemon process to pull every so often unless we need to manually pull.  Either way is fine with me.

**Comment by mrcoven94** [comment]
@frankcash , there were some words I didn't understand, in a good way! I'm down with whatever. And I'm lookin forward to your tutorials on everything you just said. haha.

**Comment by frankcash** [comment]
haha okay, well we need to decide if we need to host it on a server or just use a static GitHub page

**Comment by kritinvij** [comment]
i didnt get through half that sentence. could you write English?

Kritin Vij
University of Washington
Computer Science | Math Minor
*kritinvij@gmail.com kritinvij@gmail.com | *
http://in.linkedin.com/pub/kritin-vij/2b/176/ab0/

**Comment by mrcoven94** [comment]
Hmm. Do you think we'll need to make it dynamic? Maybe we should flesh out the frontend, and some more content, on static before we move over. Thoughts?

**Comment by kritinvij** [comment]
sounds like a good way to act.

Kritin Vij
University of Washington
Computer Science | Math Minor
*kritinvij@gmail.com kritinvij@gmail.com | *
http://in.linkedin.com/pub/kritin-vij/2b/176/ab0/

**Comment by frankcash** [comment]
Which libraries do we want to use?  Obviously BootStrap. 

Next: JS Libs:

Raw JS, jQuery, Angular or React

**Comment by mahirk** [comment]
Raw JS and Angular? I actually know really less about angular! Any of you?

**Comment by mrcoven94** [comment]
I've been meaning to get into Angular, so I'd +1 for that.  And probably a little Raw Js + JQuery

Or Ember, idk which one is better.

**Comment by mahirk** [comment]
Mee too, need motivation :p

**Comment by mrcoven94** [comment]
Lets do it @mahirk ...! Angular it is? Or ember that bad boy

**Comment by frankcash** [comment]
Just use Angular and built it as a SPA

**Comment by mrcoven94** [comment]
Also I accidentally deleted the scholarship column, and I'm too lazy to remake it for now.. even though GIT is a version control system... I can't use it at the moment, so too late.

**Comment by mrcoven94** [comment]
Leggo frank, love the idea

**Comment by frankcash** [comment]
Yeah, let's just remake this as a site...

We should create issues corresponding to what needs to get done for the purpose of allowing everyone who is interested to follow development and give their input.  Is is also important to push with the issue referenced i.e. `<commit message here> (#<issue number>)`

**Comment by mrcoven94** [comment]
I'm down, lets just start making it. Anyone wanna take the lead?

**Comment by frankcash** [comment]
I can start but I won't be able to write until late tonight/tomorrow.

**Comment by mrcoven94** [comment]
:D Sooner than me, I have 5 presentations coming up, won't be able to start until like next week haha

**Comment by kritinvij** [comment]
I can take the lead but I neither know ember nor angular a lot.. and, well,
you guys are better

Kritin Vij
University of Washington
Computer Science | Math Minor
*kritinvij@gmail.com kritinvij@gmail.com | *
http://in.linkedin.com/pub/kritin-vij/2b/176/ab0/

**Comment by frankcash** [comment]
Don't worry we can move slowly.  I want this to be a learning process for
those who want to learn.

**Comment by kritinvij** [comment]
Charles you are the best!
Can I connect with you on facebook?
https://www.facebook.com/kritin.vij

Kritin Vij
University of Washington
Computer Science | Math Minor
*kritinvij@gmail.com kritinvij@gmail.com | *
http://in.linkedin.com/pub/kritin-vij/2b/176/ab0/

**Comment by mrcoven94** [comment]
You better Kritin!

**Comment by mrcoven94** [comment]
And @frankcash, @kritinvij says things that aren't true. He is literally a master at making things awesome.

**Comment by mahirk** [comment]
@frankcash @mrcoven94 let's start on another repo? I'm not good with
designing, I'll start once I'm in Seattle tomorrow

**Comment by frankcash** [comment]
We will start another repo as part of HackerCollective.  I will create it now.
