### ISSUE TITLE
Dumb Code of Conduct Folder

### ISSUE THREAD

**Issue by mrcoven94** [HackerCollective/resources#23]
I can't remove the dumb folder, I can't clone the repo locally to rm the files.

**Comment by frankcash** [comment]
![rekt](https://cloud.githubusercontent.com/assets/6012231/4264061/e2207b34-3c12-11e4-85a9-2640841bfc59.png)

Looks like I won't be able to :(

**Comment by kritinvij** [comment]
It seems like I dont have permissions to push to this directory. Someone give me these permissions.. Maybe, then, I can remove this folder you are asking for.

**Comment by frankcash** [comment]
You should be able to now.

**Comment by kritinvij** [comment]
[image: Inline image 1]
this is really weird. it should show me the folder, right?
shows on git website only, doesnt show otherwise

Kritin Vij
University of Washington
Computer Science | Math Minor
*kritinvij@gmail.com kritinvij@gmail.com | *
http://in.linkedin.com/pub/kritin-vij/2b/176/ab0/

**Comment by frankcash** [comment]
Your image didn't load correctly @kritinvij .  And yeah I can't pull it because it is too large

**Comment by kritinvij** [comment]
well, i cloned the repo. and it doesnt show that folder with the long name
in the directory on my laptop.

Kritin Vij
University of Washington
Computer Science | Math Minor
*kritinvij@gmail.com kritinvij@gmail.com | *
http://in.linkedin.com/pub/kritin-vij/2b/176/ab0/

**Comment by frankcash** [comment]
~~I wonder if doing `git rm -r -f <file path>` will remove it even if we don't have it in our own individual repository?  Otherwise~~ we need to wait for who ever uploaded (I think @mrcoven94) to remove it since the file is too large to pull.

**Comment by kritinvij** [comment]
the file path is too long and has a bunch of "/" and other things that are
not allowed to be included in file names on OSs. That is one reason, that I
think we cant clone the file on directories.

If we can rename it. Then, maybe the remove command will work.

Kritin Vij
University of Washington
Computer Science | Math Minor
*kritinvij@gmail.com kritinvij@gmail.com | *
http://in.linkedin.com/pub/kritin-vij/2b/176/ab0/

**Comment by mrcoven94** [comment]
I can't load it locally.... :-1:

**Comment by kritinvij** [comment]
i think the only work around this thing is to rename..

Kritin Vij
University of Washington
Computer Science | Math Minor
*kritinvij@gmail.com kritinvij@gmail.com | *
http://in.linkedin.com/pub/kritin-vij/2b/176/ab0/

**Comment by mrcoven94** [comment]
Not sure how, but give it a shot :+1:

**Comment by kritinvij** [comment]
someone work with the terminal. i dont like terminal work..
http://www.patrick-wied.at/blog/rename-files-and-folders-with-git

Kritin Vij
University of Washington
Computer Science | Math Minor
*kritinvij@gmail.com kritinvij@gmail.com | *
http://in.linkedin.com/pub/kritin-vij/2b/176/ab0/

**Comment by frankcash** [comment]
I would but I can't pull it because the path is too long :^)

**Comment by kritinvij** [comment]
looks like David, you are up for this one.

**Comment by frankcash** [comment]
I wish `git add` explicitly told you if your path name was going to be too large @torvalds

**Comment by mrcoven94** [comment]
I FUCKING FIXED IT. I DELETED IT! ALL PRAISE THE MAC GITHUB CLIENT. YES <3

**Comment by frankcash** [comment]
it's about fucking time @mrcoven94 
ALL HAIL GITHUB GUI CLIENT

**Comment by mrcoven94** [comment]
ALL HAIL IT! Sorry again, now its going to be so much easier to build a site, and to develop all this shit. Man, thank the lord. haha. ALL HAIL BASED GUI.
