### ISSUE TITLE
Should we condone open-source utilities before proprietary ones?

### ISSUE THREAD

**Issue by frankcash** [HackerCollective/resources#41]
I think we should condone open-source utilities.  Like I told a friend once `friends don't let friends use proprietary tools.`  

I was reading through one of the guides and it recommended Sublime Text and I thought to myself not only is there an open-source alternative but there are better open-source alternatives.  I can understand recommending a proprietary tool if there is no open-source alternative.

**Comment by bryangarza** [comment]
I also think we should encourage open source tools, there's a culture difference between people that use proprietary tools vs foss ones, and being able to influence that, we should take the opportunity to lead them towards the right direction.

**Comment by mrcoven94** [comment]
I think using proprietary tools is fine, but I do agree that we should promote open-source alternatives, especially if they're better. The Sublime - Text was something I put down in my early days of web dev, and I just never got around to updating it.  I agree with you both! Lets do it !

**Comment by frankcash** [comment]
@bryangarza I agree with that statement

@mrcoven94  like I said I see use cases where it's fine.

**Comment by mrcoven94** [comment]
:)
